# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rnetmatch_wrappers", use_symbols = TRUE, package_name = "rnetmatch")

#' @docType package
#' @usage NULL
#' @useDynLib rnetmatch, .registration = TRUE
NULL

rnet_match_one_tree <- function(x, y, distance_tolerance, slope_tolerance, is_projected) .Call(wrap__rnet_match_one_tree, x, y, distance_tolerance, slope_tolerance, is_projected)

rnet_match_two_trees <- function(x, y, distance_tolerance, slope_tolerance, is_projected) .Call(wrap__rnet_match_two_trees, x, y, distance_tolerance, slope_tolerance, is_projected)


# nolint end
