---
format: gfm
---

For local development run this in the `r` directory:

```{r}
devtools::load_all()
```

Install it locally with:

```{r}
#| eval: false
devtools::build()
```

And clean up previous builds:

```{r}
#| eval: false
rextendr::clean()
```

```{r}
library(dplyr)
```

# Basic test

```{r}
x = sf::st_sf(
  geometry = sf::st_sfc(
    sf::st_linestring(matrix(c(1, 1, 5, 1), ncol = 2, byrow = TRUE))
  )
)

y = sf::st_sf(
  geometry = c(
    sf::st_sfc(
      sf::st_linestring(matrix(c(2, 2, 6, 2), ncol = 2, byrow = TRUE))
    ),
    sf::st_sfc(
      sf::st_linestring(matrix(c(1, 0.5, 5, 0.5), ncol = 2, byrow = TRUE))
    )
  )
)
x$object = "x"
y$object = "y"
xy = rbind(
  x,
  y
)
plot(xy)
plot(x, add = TRUE)
plot(y)
```

```{r}
matched_df = rnet_match(x, y, dist_tolerance = 1, angle_tolerance = 0, trees = "xy")
matched_df
```




# Another test

```{r}
list.files("data-raw/geojson")
x = sf::read_sf("inst/extdata/princes_street_minimal_x_1.geojson")
x = x |> sf::st_transform("EPSG:27700")
y = sf::read_sf("inst/extdata/princes_street_minimal.geojson")
y = y |> sf::st_transform("EPSG:27700")
```

```{r}
#| label: fig-x-and-y
bind_rows(
  x |>
    transmute(value = "x"),
  y |>
    transmute(value = as.character(value))
) |>
  plot(lwd = 5)
```


```{r}
nrow(x)
nrow(y)
matched_df = rnet_match(x, y, dist_tolerance = 20, angle_tolerance = 20, trees = "xy")
nrow(matched_df)
matched_df
length_x = sf::st_length(x) |>
  # Drop units:
  units::drop_units()
length_x

y_to_match = y |>
  transmute(j = 1:n(), value) |>
  sf::st_drop_geometry() 
matched_df_y = left_join(matched_df, y_to_match)
x_to_match = x |>
  transmute(i = 1:n(), length_x) |>
  sf::st_drop_geometry()
matched_df_xy = left_join(matched_df_y, x_to_match)
x_formula = matched_df_xy |>
  mutate(value_formula = value * shared_len / length_x)
x_formula
x_with_values = x_formula |>
  group_by(id = i) |>
  summarise(
    value = sum(value_formula),
    length_x = first(length_x)
    )
x_joined = left_join(x, x_with_values)
```

The total length travelled on each network can be calculated as follows:

```{r}
total_distance_x = sum(x_joined$value * x_joined$length_x)
round(total_distance_x)
```

And for `y`:

```{r}
total_distance_y = sum(as.numeric(y$value * sf::st_length(y)))
total_distance_y
```

We can post process the joined x network to get the total length travelled on each network:

```{r}
x_joined = x_joined |>
  mutate(value = value * total_distance_y / total_distance_x)
```

That results in these values:

```{r}
x_joined$value
round(x_joined$value)
```

```{r}
#| label: fig-x_joined
y |>
  select(value) |>
  plot(lwd = 5)
x_joined |>
  select(value) |>
  plot(lwd = 5)
```

```{r}
```

```{r}
```